#define WIN32_LEAN_AND_MEAN
#pragma comment(lib, "user32")
#pragma comment(lib, "shell32")
#pragma comment(lib, "shlwapi")
#pragma comment(lib, "advapi32")
#pragma comment(lib, "libmupdf")

#include <windows.h>
#include <shellapi.h>
#include <shlwapi.h>
#include "pdf_drop_seals.h"
#include "open_source.h"
#include "context_menu.h"

#define EXE_NAME "pdf-seals-deleter"
#define BUFSIZE 4096

void get_path_with_logo(char* input, char* output)
{
    char* pdf_pos = strstr(input, ".pdf");
    int prefix_len = (int)(pdf_pos - input);
    strncpy(output, input, prefix_len);
    strcat(output, "_without_seals.pdf");
}

void pop_message_box(char* fixed_exe_path)
{
    // Popup a message box to require user to confirm if kill these processes
    char subkey_file[] = "Software\\Classes\\SystemFileAssociations\\.pdf\\shell\\";
    LANGID langID = GetUserDefaultUILanguage();
    int result = (PRIMARYLANGID(langID) == LANG_CHINESE) ?
                 MessageBoxW(NULL, 
                     L"本软件可为文件资源管理器上下文菜单提供一条命令，用于消除 PDF 文件水印。"
                     L"用户可通过右键 PDF 文件选中相关命令以在当前文件夹生成无水印 PDF 文件"
                     L"（<原文件名>_without_seals.pdf）。\n"
                     L"---------------\n"
                     L"本软件原理为提取原 PDF 文件中所有图片，筛选掉其中宽度大于高度的图片，"
                     L"最后拼接生成新 PDF 文件。因此只支持消除此对应逻辑生成的水印。\n"
                     L"---------------\n"
                     L"选项说明：\n"
                     L"    是（YES）：添加/更新上下文菜单；\n"
                     L"    否（NO）：删除上下文菜单；\n"
                     L"    取消（Cancel）：不作为，直接退出。\n"
                     L"---------------\n"
                     L"命令行以参数 `--source` 运行查看依赖、许可证以及源码。\n"
                     L"---------------\n"
                     L"版本：2025-3-15\n",
                     L"使用说明", MB_YESNOCANCEL | MB_TOPMOST) : 
                 MessageBoxW(NULL, 
                     L"This software provides a command for the file explorer context menu to remove watermarks from PDF files. "
                     L"Users can right-click on a PDF file and select the relevant command to generate a watermark-free PDF file "
                     L"(<OriginalFileName>_without_seals.pdf) in the current folder.\n"
                     L"---------------\n"
                     L"The principle of this software is to extract all images from the original PDF file, filter out images "
                     L"where the width is greater than the height, and finally merge them into a new PDF file. Therefore, it only "
                     L"supports removing watermarks generated by this specific logic.\n"
                     L"---------------\n"
                     L"Options description:\n"
                     L"    Yes (YES): Add/Update context menu;\n"
                     L"    No (NO): Remove context menu;\n"
                     L"    Cancel: Do nothing and exit.\n"
                     L"---------------\n"
                     L"Run the command line with the parameter --source to view dependencies, licenses, and source code.\n"
                     L"---------------\n"
                     L"Version: 2025-3-15",
                     L"Usage Instructions", MB_YESNOCANCEL | MB_TOPMOST);
    if (result == IDYES) {
        // Get current exe path and copy to fixed location
        char exe_path[MAX_PATH];
        GetModuleFileNameA(NULL, exe_path, MAX_PATH);
        copy_to_fixed_location(exe_path, fixed_exe_path);
        // Add fixed exe path to context menu
        char* menu_text = (PRIMARYLANGID(langID) == LANG_CHINESE) ? "消除水印" : "Remove seals";
        add_context_menu(EXE_NAME, menu_text, subkey_file, fixed_exe_path);
    } else if (result == IDNO) {
        // Delete exe of fixed location
        if (PathFileExistsA(fixed_exe_path)) {
            DeleteFileA(fixed_exe_path);
            // Delete parent directory (if is empty)
            char dir_path[MAX_PATH];
            strcpy(dir_path, fixed_exe_path);
            PathRemoveFileSpecA(dir_path);
            RemoveDirectoryA(dir_path);
        }
        // Remove context menu
        remove_context_menu(EXE_NAME, subkey_file);
    }
}


LRESULT CALLBACK WindowProc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
{
    switch (uMsg) {
    case WM_DESTROY:
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcW(hwnd, uMsg, wParam, lParam);
}

int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPWSTR lpCmdLine, int nCmdShow)
{
    // Set DPI awareness for better scaling on high DPI displays (Windows 10, v1607)
    SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);

    // Register window class
    WNDCLASSW wc = { 0 };
    wc.lpfnWndProc = WindowProc;
    wc.hInstance = hInstance;
    wc.lpszClassName = L"PDF Seals Deleter";
    wc.hIcon = LoadIconW(hInstance, MAKEINTRESOURCEW(1));

    RegisterClassW(&wc);

    // If run by context menu, delete seals
    if (*lpCmdLine) {
        char cmd_line[MAX_PATH] = { 0 };
        WideCharToMultiByte(CP_UTF8, 0, lpCmdLine, -1, cmd_line, sizeof(cmd_line), NULL, NULL);
        if (strcmp(cmd_line, "--source") == 0) {
            extract_source("pdf_seals_deleter_source.zip");
        } else {
            cmd_line[strlen(cmd_line)-1] = '\0';
            char* pdf_path = cmd_line+1;
            char output_path[MAX_PATH] = { 0 };
            get_path_with_logo(pdf_path, output_path);
            pdf_drop_seals(pdf_path, output_path);
        }
    } else {
        char fixed_exe_path[MAX_PATH] = { 0 };
        get_fixed_exe_path(EXE_NAME, fixed_exe_path);
        pop_message_box(fixed_exe_path);
    }

    ExitProcess(0);

    return 0;
}
